conjunto_operaciones_ener = {
"Gastos software de terceros.",
"Comisiones mercantiles.",
"Nomina",
"Nomina",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Gastos por servicios financieros.",
"Otros gastos.",
"Gastos por telefonia e internet.",
"Gastos por telefonia e internet.",
"PAGO.",
"PAGO.",
"PAGO.",
"Acuse de cancelación de CFDI",
"Acuse de cancelación de CFDI",
"Acuse de cancelación de CFDI",
"Acuse de cancelación de CFDI",
"otros gastos.",
"Impuestos diversos.",
"Gastos software de terceros.",
"Servicios de mantenimiento",
"Honorarios pagados.",
"PAGO.",
"Arrendamientos.",
"PAGO.",
"Comisiones mercantiles.",
"Honorarios pagados.",
"Honorarios pagados.",
"Honorarios pagados.",
"Honorarios pagados.",
"Honorarios pagados.",
"PAGO.",
"Otros gastos.",
"Gastos software de terceros.",
"Otros gastos.",
"Aportaciones.",
"Impuestos diversos.",
"Honorarios pagados.",
"Honorarios pagados.",
"Honorarios pagados.",
"Honorarios pagados.",
"Honorarios pagados.",
"Comisiones mercantiles.",
"Comisiones mercantiles.",
"Otros gastos.",
"Papeleria y utiles.",
"Papeleria y utiles.",
"Papeleria y utiles.",
"Honorarios pagados.",
"Impuestos diversos.",
"Servicios de mantenimiento",
"Gastos software de terceros.",
"Arrendamientos.",
"Servicios de mantenimiento",
"PAGO.",
"Servicios de mantenimiento",
"Servicios de mantenimiento",
"PAGO.",
}

a = "/c/Users/Luis Carlos Gomez/Rigoberto/OneDrive - CORREDURIA 38 S.C/Contabilidad Promotora Profile/Sistematizacion de correos"
"(/c/Users/Luis Carlos Gomez/.ssh/id_ed25519)"
with open("conjunto operaciones enero.txt", "w", encoding="UTF-8") as f:
    for operacion in conjunto_operaciones_ener:
        f.write(f"{operacion}\n")